version: '3.9'

networks:
  net:
    driver: bridge
    name: qnallm

services:
  app:
    build: ./
    image: myfastapiapp
    container_name: fastapi_container
    restart: always
    volumes:
      - ./src:/app:ro
    ports:
      - "8000:8000"
    networks:
      - net
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
